[[heading]]
# Common Language Infrastructure (CLI) 
level = 1
greedy = true
font.name = "Times New Roman,Bold"
font.size = 18.0
# font.size_tolerance = 1e-5
# font.color = 0x0000ff
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 90.02399444580078
# bbox.top = 107.70001220703125
# bbox.right = 410.1719665527344
# bbox.bottom = 127.63360595703125
# bbox.tolerance = 1e-5

[[heading]]
# I.1
level = 2
greedy = false
font.name = "Times New Roman,Bold"
font.size = 12.0
# font.size_tolerance = 1e-5
# font.color = 0x000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 90.02401733398438
# bbox.top = 78.36663818359375
# bbox.right = 105.60001373291016
# bbox.bottom = 91.65570068359375
# bbox.tolerance = 1e-5

[[heading]]
# I.4.1
level = 3
greedy = true
font.name = "Times New Roman,Bold"
font.size = 11.039999961853027
# font.size_tolerance = 1e-5
# font.color = 0x000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 90.02401733398438
# bbox.top = 98.18212890625
# bbox.right = 114.69841766357422
# bbox.bottom = 110.40806579589844
# bbox.tolerance = 1e-5

[[heading]]
# Exceptions thrown by the CLI  
level = 4
greedy = true
font.name = "Times New Roman,Bold"
font.size = 9.960000038146973
# font.size_tolerance = 1e-5
# font.color = 0x000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 162.02000427246094
# bbox.top = 324.53448486328125
# bbox.right = 325.60302734375
# bbox.bottom = 335.56439208984375
# bbox.tolerance = 1e-5

